### DISCUSSION TITLE
How to configurate Cloudflare R2

### DISCUSSION THREAD

**Discussion by lord007tn** [docmost/docmost#1044] [Help / Questions]
i believe am doing everything right.

same config works in other apps like coolify/ nocodb ...
but not in docmost

i followed the docs, and i can't make it work

**Comment by martyh** [comment]
This worked for me in the docker-compose.yml file:

```
services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: '<redacted>'
      APP_SECRET: '<redacted>'
      DATABASE_URL: 'postgresql://docmost:<redacted>@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
      STORAGE_DRIVER: s3
      AWS_S3_ACCESS_KEY_ID: '<redacted>'
      AWS_S3_SECRET_ACCESS_KEY: '<redacted>'
      AWS_S3_REGION: auto
      AWS_S3_BUCKET: docmost-storage
      AWS_S3_ENDPOINT: 'https://<account-id>.r2.cloudflarestorage.com'
      AWS_S3_FORCE_PATH_STYLE: true
    ports:
      - "3000:3000"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: '<redacted>'
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:


```
