### DISCUSSION TITLE
Docmost SMTP Help Guide

### DISCUSSION THREAD

**Discussion by XJY00** [docmost/docmost#1198] [General]
When configuring smtp, 
first write the configuration in the environment of the docker-compose.yml file, not .env file.
and the parameters can be customized according to the docmost documentation.
If you want the updated configuration to take effect, 
you need to `docker-compose down` first and then `docker-compose up -d`,
instead of `docker-compose reload` or `docker-compose restart`.

配置smtp时，
首先在docker-compose.yml中的environment中进行配置，而不是.env文件。
并且参数可以根据docmost文档自定义。
如果您希望更新后的配置生效，
你需要先‘docker-compose down’，然后‘docker-compose up -d’，
而不是‘ docker-compose reload ’或‘ docker-compose restart ’。

#### Sample configuration
```
version: '3'

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'https://doc.x.x'
      APP_SECRET: 'x'
      DATABASE_URL: 'postgresql://docmost:password@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
      FILE_UPLOAD_SIZE_LIMIT: 500mb
      MAIL_DRIVER: 'smtp'
      MAIL_FROM_ADDRESS: 'x@email.com'
      MAIL_FROM_NAME: 'Docmost'
      SMTP_HOST: 'smtp.x.com'
      SMTP_PORT: '587/465'
      SMTP_USERNAME: 'x@email.com'
      SMTP_PASSWORD: ''
      # SMTP_SECURE: 'true'
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./docmost:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - ./redis_data:/data

# volumes:
#   docmost:
#   db_data:
#   redis_data:
```
