### DISCUSSION TITLE
ERROR [DatabaseModule] error: password authentication failed for user

### DISCUSSION THREAD

**Discussion by ronycohen** [docmost/docmost#447] [Help / Questions] [answered]
I think the application don't connect properly to the Database : 
After a proper : `docker system prune -a` command I launched a `docker compose up -d`

![image](https://github.com/user-attachments/assets/86cbe670-6d11-418f-b7ba-7adc96410bfd)

Here is the docker compose : 
```
version: '3'

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://docmost.local:3000'
      APP_SECRET: '1a8d76983a7169c7f26ddb88177397114e854be93634689f852cc72d272c822e'
      DATABASE_URL: 'postgresql://docmost:docmost@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: docmost
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data:
```
