### DISCUSSION TITLE
docker-compose.yml with traefik running on the dockerhost

### DISCUSSION THREAD

**Discussion by voltronunited** [docmost/docmost#488] [Help / Questions]
Somehow I can't figure out how to set this up on a dockerhost on which traefik is running. I get a success page "Success!
Your new web server is ready to use." but nothing more, nothing less... thank you very much for your help

```
version: '3'

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://docmost.domain.com'
      APP_SECRET: 'SUPER_STRONG_APP_KEY'
      DATABASE_URL: 'postgresql://docmost:STRONG_PW@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "3000:3000"
    restart: unless-stopped
    labels:
      - "traefik.http.routers.docmost.rule=Host(`docmost.domain.com`)" 
      - "traefik.http.routers.docmost.entrypoints=web" 
        #- "traefik.http.routers.docmost.tls.certresolver=myresolver" 
      - "traefik.http.services.docmost.loadbalancer.server.port=3000" 
    networks:
      - traefik-net
    volumes:
      - docmost:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: STRONG_PW
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data:


networks:
  traefik-net:
    external: true
```
