### DISCUSSION TITLE
setting s3

### DISCUSSION THREAD

**Discussion by bulava92** [docmost/docmost#607] [Help / Questions]
![untitled](https://github.com/user-attachments/assets/74b0f5bd-c9ab-459b-b3ac-f6bf7f890754)

Hello

Set up s3

From the computer the files are normally loaded into it, but from the iOS phone there is no and some kind of error appears, what to do?

```
version: "3"

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: "http://localhost:3000"
      APP_SECRET: "111"
      DATABASE_URL: "111"
      REDIS_URL: "redis://redis:6379"
      STORAGE_DRIVER: "s3"
      AWS_S3_ACCESS_KEY_ID: "111"
      AWS_S3_SECRET_ACCESS_KEY: "111"
      AWS_S3_REGION: "111"
      AWS_S3_BUCKET: "111"
      AWS_S3_ENDPOINT: "https://111"
```
