### DISCUSSION TITLE
Internal server error

### DISCUSSION THREAD

**Discussion by KlarOFF** [docmost/docmost#676] [Help / Questions]
I'm using Portainer and Nginx Proxy Manager to deploy Docmost.
But I have "Internal server error", when I'm trying to create workspace. 
Here is logs after showing error:

```
[Nest] 41  - 01/24/2025, 5:37:05 AM   ERROR [ExceptionsHandler] password authentication failed for user "docmost"
error: password authentication failed for user "docmost"
    at /app/node_modules/.pnpm/pg-pool@3.7.0_pg@8.13.1/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresDriver.acquireConnection (/app/node_modules/.pnpm/kysely@0.27.4/node_modules/kysely/dist/cjs/dialect/postgres/postgres-driver.js:21:24)
    at async RuntimeDriver.acquireConnection (/app/node_modules/.pnpm/kysely@0.27.4/node_modules/kysely/dist/cjs/driver/runtime-driver.js:46:28)
    at async DefaultConnectionProvider.provideConnection (/app/node_modules/.pnpm/kysely@0.27.4/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:10:28)
    at async DefaultQueryExecutor.executeQuery (/app/node_modules/.pnpm/kysely@0.27.4/node_modules/kysely/dist/cjs/query-executor/query-executor-base.js:36:16)
    at async SelectQueryBuilderImpl.execute (/app/node_modules/.pnpm/kysely@0.27.4/node_modules/kysely/dist/cjs/query-builder/select-query-builder.js:317:24)
    at async SelectQueryBuilderImpl.executeTakeFirst (/app/node_modules/.pnpm/kysely@0.27.4/node_modules/kysely/dist/cjs/query-builder/select-query-builder.js:321:26)
    at async WorkspaceRepo.count (/app/apps/server/dist/database/repos/workspace/workspace.repo.js:64:27)
    at async SetupGuard.canActivate (/app/apps/server/dist/core/auth/guards/setup.guard.js:20:32)
    at async GuardsConsumer.tryActivate (/app/node_modules/.pnpm/@nestjs+core@10.4.9_@nestjs+common@10.4.9_class-transformer@0.5.1_class-validator@0.14.1_refl_zsbc4rwqpxjpmlf7ki7strvkxu/node_modules/@nestjs/core/guards/guards-consumer.js:16:17)
    at async canActivateFn (/app/node_modules/.pnpm/@nestjs+core@10.4.9_@nestjs+common@10.4.9_class-transformer@0.5.1_class-validator@0.14.1_refl_zsbc4rwqpxjpmlf7ki7strvkxu/node_modules/@nestjs/core/router/router-execution-context.js:135:33)
    at async /app/node_modules/.pnpm/@nestjs+core@10.4.9_@nestjs+common@10.4.9_class-transformer@0.5.1_class-validator@0.14.1_refl_zsbc4rwqpxjpmlf7ki7strvkxu/node_modules/@nestjs/core/router/router-execution-context.js:42:31
    at async Object.<anonymous> (/app/node_modules/.pnpm/@nestjs+core@10.4.9_@nestjs+common@10.4.9_class-transformer@0.5.1_class-validator@0.14.1_refl_zsbc4rwqpxjpmlf7ki7strvkxu/node_modules/@nestjs/core/router/router-proxy.js:9:17)
```

And if I press the button "Create Workspace" three times, the workspace will be create. And almost all actions (for example updating page, or toggle "Full Width", send invite link) in workspace I have to do three times and then it will works. Almost every action I see "Internal server error" and  _error: password authentication failed for user "docmost"_ in logs.

I'm was trying to resolve issue like [here](https://github.com/docmost/docmost/issues/96) and [here](https://github.com/docmost/docmost/issues/87), but it still dosen't works.

My compose:
```yml
version: "3"

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: "https://my.domain.com"
      APP_SECRET: "MY_APP_SECRET"
      DATABASE_URL: postgresql://docmost:MY_DB_PASS_WITHOUT_CHARACTERS@db:5432/docmost?schema=public
      REDIS_URL: "redis://redis:6379"
      MAIL_DRIVER: "smtp"
      SMTP_HOST: "smtp.domain.com"
      SMTP_PORT: 587
      SMTP_USERNAME: "my@email.com"
      SMTP_PASSWORD: "SMTP_APP_PASS"
      SMTP_SECURE: "false"
      MAIL_FROM_ADDRESS: "my@email.com"
      MAIL_FROM_NAME: "Docmost"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage
    networks:
      - default

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: MY_DB_PASS_WITHOUT_CHARACTERS
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - default

volumes:
  docmost:
  db_data:
  redis_data:
  
networks:
  default:
    name: mynetwork
    external: true
```
