### DISCUSSION TITLE
[BUG] Error 415 (Unsupported Media Type) on front end via Reverse Proxy

### DISCUSSION THREAD

**Discussion by morganwk** [docmost/docmost#743] [Help / Questions]
I just got Docmost working (after no small amount of troubleshooting stemming from already having at least one other docker container using postgres and redis) but I'm currently stuck at exposing the web UI over my domain.

The localhost URL seems to work just fine, but I'd really like to get it working over a reverse proxy.

Environment / Steps to reproduce:

- Docker CLI on Kubuntu, AMD64
- large docker-compose.yaml file including config for many other services, several of which run instances of postgresql and redis
- include docmost-compose.yaml: (redacted)
```yaml
services:
  docmost:
    container_name: docmost
    image: docmost/docmost:latest
    depends_on:
      - docmost-db
      - docmost-redis
    environment:
      APP_URL: "http://localhost:3000"
      APP_SECRET: "[redacted]"
      DATABASE_URL: "postgresql://docmost:[password redacted]@[internal ip]:5433/docmost?schema=public"
      REDIS_URL: "redis://[internal ip]:6378"
    ports:
      - "3009:3000"
    restart: unless-stopped
    volumes:
      - /homelab/container-data/docmost/app:/app/data/storage

  docmost-db:
    container_name: docmost-db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost-db
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: [password redacted]
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - /homelab/container-data/docmost/db:/var/lib/postgresql/data

  docmost-redis:
    container_name: docmost-redis
    image: redis:7.2-alpine
    ports:
      - "6378:6379"
    restart: unless-stopped
    volumes:
      - /homelab/container-data/docmost/redis_data:/data
```
- successfully connect via localhost url
- add reverse proxy endpoint (in my case via zoraxy)
- attempt connection via external domain
- blank white page loads
- check console, see: `XHR POST https://docmost.[domain.com]/api/users/me        [HTTP/3 416 66ms]`

Unsure of how to proceed. I saw a few other issues mentioning a similar error but they all appear to have been symptoms of a different cause.
