### DISCUSSION TITLE
Uploaded Images Not Found (0.8.1)

### DISCUSSION THREAD

**Discussion by arcticblizzard** [docmost/docmost#758] [Help / Questions]
First off - love this project, I've converted some of my Bookstack wikis to this platform as it better fits my needs.

I had started some pages while I was in 0.7 awhile back, and few included images. After updating to v0.8.1 today, the images have returned back as 404's. The URL as an example:  http://192.168.172.3:8686/api/files/0194c7f4-f138-7711-a623-b5995f354521/oct-final.jpg

and the JSON response:  {"message":"File not found","error":"Not Found","statusCode":404}

I did upload a test image and the updated URL does have a different GUID (or what I assume is a GUID):
http://192.168.172.3:8686/api/files/0194c7f4-f138-7711-a623-b5995f354521/oct-final.jpg

As part of upgrading to 0.8.1 I did have to change my APP_SECRET, but I am unsure if this had an impact. Is there a way to easily restore my images, or will I have to re-upload all of my images?

Thanks!

**Comment by Philipinho** [comment]
What storage are you using?
Did you make any changes to the storage driver?

**Reply by arcticblizzard** [reply]
The Docker containers (docmost, postgres, redis) are running on unRAID and their storage config hasn't changed between my update; they have always been pointed to "/mnt/user/appdata/docmost". I haven't made any changes to the storage driver either.

**Reply by Philipinho** [reply]
i. Can you find the physical files in the storage location?
https://github.com/docmost/docmost/blob/3e5cb92621d78265d6d036b7d765d93372e19b75/Dockerfile#L46
ii. Are there file entries in the database `attachments` table?

**Reply by arcticblizzard** [reply]
Okay - did a bit more digging.

1. I found the attachment records in the postgres database
2. I was unable to list any files in the /app/data/storage location (within the docmost container) or its accompanying mount point in unRAID
3. I did find errors in the docmost log "Error [AttachmentController[ Error: Failed to read file: ENOENT: no such file or directory...  I've attached the stderr logs.
[docmost_log_img_error.txt](https://github.com/user-attachments/files/18897097/docmost_log_img_error.txt)

**Reply by Philipinho** [reply]
Run `docker volume ls` and let me know if there is a volume named `docmost`.

**Reply by arcticblizzard** [reply]
Running ```docker volume ls``` resulted in a list of volumes, but they are all GUIDS ("1ab3808cf6c24cf811e4de4814f043f73f992d51f8ba0d456263cfed43598cec" as an example). This is most likely a function of unRAID.

I did also run ```docker inspect docmost | grep -A 5 "Mounts"``` and got the following:

```
"Mounts": [
            {
                "Type": "bind",
                "Source": "/mnt/user/appdata/docmost/data",
                "Destination": "/data",
                "Mode": "rw",
```
When navigating to the Source directory, ```ls``` does not return any records.

**Reply by Philipinho** [reply]
I would love the see the docker compose setup you are using. It seems persistent volume was not created for Docmost. ]
We do this in our compose file.

https://github.com/docmost/docmost/blob/08829ea721650169be7ea20cc29489e0f87bb77c/docker-compose.yml#L17-L18

https://github.com/docmost/docmost/blob/08829ea721650169be7ea20cc29489e0f87bb77c/docker-compose.yml#L36-L39

**Reply by arcticblizzard** [reply]
Thanks for taking the time to review my problem. I am relatively new to Docker, so I wouldn't be surprised if I did something silly in creating my compose file (below):

```
version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: docmost_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost_user
      POSTGRES_PASSWORD: xxxx
    volumes:
      - /mnt/user/appdata/docmost/postgres:/var/lib/postgresql/data
    networks:
      - default  # Ensure PostgreSQL is in the same network


  redis:
    image: redis:latest
    container_name: docmost_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - /mnt/user/appdata/docmost/redis:/data
    networks:
      - default

  docmost:
    image: docmost/docmost:latest
    container_name: docmost
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://docmost_user:xxxx@docmost_postgres:5432/docmost"
      REDIS_URL: "redis://docmost_redis:6379"
      APP_SECRET: "xxxx"
      PORT: "8080"
    depends_on:
      - postgres
      - redis
    ports:
      - "8686:8080"
    volumes:
      - /mnt/user/appdata/docmost/data:/data
    networks:
      - default


networks:
  docmost_net:
    driver: bridge

```
