### DISCUSSION TITLE
Failed to upload images/files

### DISCUSSION THREAD

**Discussion by LucasCtrl** [docmost/docmost#858] [Help / Questions]
Using Docmost with MinIO to store files.
During image upload, I always have the error `Error: Failed to upload file: char '4' is not expected.:1:1`.
Same issue when uploading file.

Full error message.
```sh
docmost  | [Nest] 41  - 03/09/2025, 7:53:59 PM   ERROR [AttachmentService] Error uploading file to drive:
docmost  | [Nest] 41  - 03/09/2025, 7:53:59 PM   ERROR [AttachmentService] Error: Failed to upload file: char '4' is not expected.:1:1
docmost  |   Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
docmost  |     at S3Driver.upload (/app/apps/server/dist/integrations/storage/drivers/s3.driver.js:26:19)
docmost  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
docmost  |     at async StorageService.upload (/app/apps/server/dist/integrations/storage/storage.service.js:25:9)
docmost  |     at async AttachmentService.uploadToDrive (/app/apps/server/dist/core/attachment/services/attachment.service.js:152:13)
docmost  |     at async AttachmentService.uploadFile (/app/apps/server/dist/core/attachment/services/attachment.service.js:60:9)
docmost  |     at async AttachmentController.uploadFile (/app/apps/server/dist/core/attachment/attachment.controller.js:82:34)
docmost  | [Nest] 41  - 03/09/2025, 7:53:59 PM   ERROR [AttachmentController] BadRequestException: Error uploading file to drive
docmost  |     at AttachmentService.uploadToDrive (/app/apps/server/dist/core/attachment/services/attachment.service.js:156:19)
docmost  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
docmost  |     at async AttachmentService.uploadFile (/app/apps/server/dist/core/attachment/services/attachment.service.js:60:9)
docmost  |     at async AttachmentController.uploadFile (/app/apps/server/dist/core/attachment/attachment.controller.js:82:34) {
docmost  |   response: {
docmost  |     message: 'Error uploading file to drive',
docmost  |     error: 'Bad Request',
docmost  |     statusCode: 400
docmost  |   },
docmost  |   status: 400,
docmost  |   options: {}
docmost  | }
```

I don't know if I miss configured Docmost or if an error is present in the codebase.
Here's my current connfiguration.

```yml
services:
  docmost:
    container_name: docmost
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: "http://localhost:4321"
      APP_SECRET: ""
      DATABASE_URL: ""
      REDIS_URL: "redis://redis:6379"
      STORAGE_DRIVER: s3
      AWS_S3_ACCESS_KEY_ID: ""
      AWS_S3_SECRET_ACCESS_KEY: ""
      AWS_S3_REGION: default
      AWS_S3_BUCKET: docmost
      AWS_S3_ENDPOINT: https://s3.XXX.XX
      AWS_S3_FORCE_PATH_STYLE: true
    ports:
      - "4321:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: ""
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data:
```

Happy to provide more information if needed.
