### DISCUSSION TITLE
Connection refused when attempting to setup Docmost

### DISCUSSION THREAD

**Discussion by bverkron** [docmost/docmost#995] [Help / Questions] [answered]
Based on the error this would seem like an obvious issues with my setup, but there's nothing in the logs to indicate an issue and I've never run into this issue before when deploy any other self hosted service (I have 20-30 services running successfully on the same server with the same deployment method (docker compose via Dockge)

I'm a bit stumped as to why docmost is giving me trouble when there's nothing indicative of a problem in the logs. I cannot hit it in the browser (`ERR_CONNECTION_REFUSED`) and cannot curl it either but can hit any other service running on that host just fine. No local firewall, etc.
```
$ curl http://10.88.10.101:3011
curl: (7) Failed to connect to 10.88.10.101 port 3011 after 0 ms: Connection refused
```

```
$ netstat -tuplen | grep 3011
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:3011            0.0.0.0:*               LISTEN      0          109565293  -                   
tcp6       0      0 :::3011                 :::*                    LISTEN      0          109567368  - 
```

Here is the compose file with some dummy values to just try and get it spun up. Port change to avoid conflict with existing service on port 3000
```yaml
version: "3"
services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: http://localhost:3011
      APP_SECRET: 32l45kjsldajflkasdjflkj23lkjalksdjflkaj
      DATABASE_URL: postgresql://docmost:34jk5hkjsfhkjqhk2jhrkjqwhefkjsahdfkjhsakjfh23@db:5432/docmost?schema=public
      REDIS_URL: redis://redis:6379
    ports:
      - 3011:3011
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: 34jk5hkjsfhkjqhk2jhrkjqwhefkjsahdfkjhsakjfh23
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
volumes:
  docmost: null
  db_data: null
  redis_data: null
networks: {}
```

And logs from all 3 containers

docmost
```yaml
$ docker logs docmost-debug-docmost-1 

> docmost@0.9.0 start /app
> pnpm --filter ./apps/server run start:prod


> server@0.9.0 start:prod /app/apps/server
> cross-env NODE_ENV=production node dist/main

[Nest] 41  - 04/05/2025, 9:14:24 PM     LOG [NestFactory] Starting Nest application...
[Nest] 41  - 04/05/2025, 9:14:24 PM     LOG [DatabaseModule] Establishing database connection
[Nest] 41  - 04/05/2025, 9:14:24 PM     LOG [DatabaseModule] Database connection successful
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20240324T085400-uuid_v7_fn" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20240324T085500-workspaces" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20240324T085600-users" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20240324T085700-groups" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20240324T085900-spaces" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20240324T086100-add-workspace-fk" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20240324T086200-workspace_invitations" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20240324T086300-pages" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20240324T086400-page_history" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20240324T086600-comments" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20240324T086700-attachments" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20240324T086800-pages-tsvector-trigger" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20240707T145623-drop-redundant-pages-slug_id-index" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20240903T124647-user-tokens" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20241218T223249-backlinks" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20250106T195516-billing" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20250118T194658-sso-auth" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [DatabaseMigrationService] Migration "20250222T114520-add_license_key_to_workspace" executed successfully
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [NestApplication] Nest application successfully started
[Nest] 41  - 04/05/2025, 9:14:25 PM     LOG [NestApplication] Listening on http://127.0.0.1:3000 / http://localhost:3011
```

postgres
```yaml
$ docker logs docmost-debug-db-1 
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... UTC
creating configuration files ... ok
running bootstrap script ... ok
sh: locale: not found
2025-04-05 21:14:16.561 UTC [36] WARNING:  no usable system locales were found
performing post-bootstrap initialization ... ok
syncing data to disk ... ok


Success. You can now start the database server using:

initdb: warning: enabling "trust" authentication for local connections
    pg_ctl -D /var/lib/postgresql/data -l logfile start
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.

waiting for server to start....2025-04-05 21:14:17.753 UTC [42] LOG:  starting PostgreSQL 16.8 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
2025-04-05 21:14:17.755 UTC [42] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-04-05 21:14:17.765 UTC [45] LOG:  database system was shut down at 2025-04-05 21:14:17 UTC
2025-04-05 21:14:17.781 UTC [42] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
```

redis
```yaml
$ docker logs docmost-debug-redis-1 
1:C 05 Apr 2025 21:14:15.351 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:C 05 Apr 2025 21:14:15.351 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 05 Apr 2025 21:14:15.351 * Redis version=7.2.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 05 Apr 2025 21:14:15.351 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 05 Apr 2025 21:14:15.352 * monotonic clock: POSIX clock_gettime
1:M 05 Apr 2025 21:14:15.352 * Running mode=standalone, port=6379.
1:M 05 Apr 2025 21:14:15.353 * Server initialized
1:M 05 Apr 2025 21:14:15.353 * Ready to accept connections tcp
```
