### ISSUE TITLE
Uploaded images not visible in docker volume

### ISSUE THREAD

**Issue by arnabJ** [docmost/docmost#1060]
I manually uploaded an image and even tried copy pasting image to a page. The upload gets completed and the image is visible on the page. But when I go to the docker volume directory (I have setup a custom path), I can't see a single file. When I do d`ocker exec` to the container and goto /app/data/storage, I am able to see all the directories and uploaded files.

My docker-compose.yml (The UID and GID is set to 0 (zero for root)):
```yml

services:
    docmost:
        image: docmost/docmost:latest
        container_name: docmost
        restart: unless-stopped
        user: "${UID}:${GID}"
        volumes:
            - ~/docker/volumes/docmost/data:/app/data/storage
        networks:
            - traefik
        environment:
            APP_URL: ${APP_URL}
            APP_SECRET: ${APP_SECRET}
            JWT_TOKEN_EXPIRES_IN: ${TOKEN_VALIDITY}
            DATABASE_URL: ${DATABASE_URL}
            REDIS_URL: ${REDIS_URL}
            MAIL_DRIVER: ${MAIL_DRIVER}
            SMTP_HOST: ${SMTP_HOST}
            SMTP_PORT: ${SMTP_PORT}
            SMTP_USERNAME: ${SMTP_USER}
            SMTP_PASSWORD: ${SMTP_PASSWORD}
            SMTP_SECURE: ${SMTP_SECURE}
            MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
            MAIL_FROM_NAME: ${MAIL_FROM_NAME}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.docmost.rule=Host(`xxxxxxxxxxxxxxx`)"
            - "traefik.http.routers.docmost.entrypoints=websecure"
            - "traefik.http.routers.docmost.tls.certresolver=letsencrypt"

networks:
    traefik:
        external: true


```
