### ISSUE TITLE
Images and video don't upload

### ISSUE THREAD

**Issue by ados8** [docmost/docmost#111]
I know there has been a previous raised issue [here](https://github.com/docmost/docmost/issues/15), however the issue is still there on 0.2.7.
I can attempt any image or video upload from public URL or internal IP and it fails.
Does this regardless of Chromium or Firefox.
Having to place URLs to images which is very clunky, will this be fixed soon?

**Comment by SteveSmall2024** [comment]
I had the same problem and following points fixed it:
1. If you use bind mounts instead of named volumes for the "/app/data/storage" volume, you need to set the User UID /GID in Docker Compose file: on host's console use "id" to find out the UID and GID of root (or the user that runs docker) and add the parameter _user: "{UID}:{GID}"_  to the "docmost" service in docker compose. Otherwise the app cannot create the necessary directories and files under the bind-mount directory. If you use named volumes it should work without the parameter.
2.  If you use NGINX-Proxy-Manager for SSL and public URL, you need to activate "Websockets Support" on the "Details" tab of your proxy host. Without that I had problems to upload files and import md/html-based content. 

Hopefully this helps!

By the way, a note to the development team: VERY COOL TOOL!!!! Thanks a lot for this great work!!!

**Comment by hao159** [comment]
just type: `sudo chown -R user:user ./path-to-docmost-data`

(user runer docker)

**Comment by ados8** [comment]
Can't believe I didn't think of that, I had the GID and UID set but the docker ignores it.
Checked and runs as 1000:1000 so a permission tweak and now it works.
Thanks @SteveSmall2024

**Comment by Rom0067** [comment]
> I had the same problem and following points fixed it:
> 
> 1. If you use bind mounts instead of named volumes for the "/app/data/storage" volume, you need to set the User UID /GID in Docker Compose file: on host's console use "id" to find out the UID and GID of root (or the user that runs docker) and add the parameter _user: "{UID}:{GID}"_  to the "docmost" service in docker compose. Otherwise the app cannot create the necessary directories and files under the bind-mount directory. If you use named volumes it should work without the parameter.
> 2. If you use NGINX-Proxy-Manager for SSL and public URL, you need to activate "Websockets Support" on the "Details" tab of your proxy host. Without that I had problems to upload files and import md/html-based content.
> 
> Hopefully this helps!
> 
> By the way, a note to the development team: VERY COOL TOOL!!!! Thanks a lot for this great work!!!



Im sorry to necro a old issue but can you please show me an example of adding uid gid to a docker compose file?  I tried everything I can think of and I keep getting permission errors.... I like using bind mounts because I find it easier to back up.  I would really appreciate the help.

**Comment by SteveSmall2024** [comment]
@Rom0067 Here is an excerpt of my docker compose.
In my case, I run it as a Stack in Portainer:

```
    (...)
    ports:
      - "3000:3000"
    restart: unless-stopped

    # Determine UID and GID of the root User on the console via command "id" 
    # You must be logged in or sudo'ed as root or the user who runs Portainer!
    # Example Result of "id" on console:       uid=0(root) gid=0(root) Gruppen=0(root)
    user: "0:0"

    volumes:
      - /yourpathto/docmost/app_storage:/app/data/storage
    (...)
```

Hope that helps!
