### ISSUE TITLE
Greeting never received

### ISSUE THREAD

**Issue by assada** [docmost/docmost#131]
Cant configure SMTP.

<img width="1283" alt="image" src="https://github.com/user-attachments/assets/136a510a-b43a-4eac-b54e-3e11816453bd">

my config: 
```yaml
environment:
      APP_URL: 'https://doc.secret.guru'
      APP_SECRET: 'secret'
      DATABASE_URL: 'postgresql://docmost:secret@docmost-db:5432/docmost?schema=public'
      REDIS_URL: 'redis://docmost-redis:6379'
      MAIL_DRIVER: smtp
      SMTP_HOST: mail.secret.services
      SMTP_PORT: 465
      SMTP_SECURE: true
      SMTP_USERNAME: projects@secret.services
      SMTP_PASSWORD: secret
      MAIL_FROM_ADDRESS: projects@secret.services
      MAIL_FROM_NAME: Secret
```

my 100% valid config for redmine (and it works) just in case..

```yaml
SMTP_ENABLED: true
SMTP_METHOD: smtp
SMTP_DOMAIN: secret.services
SMTP_HOST: mail.secret.services
SMTP_PORT: 465
SMTP_USER: projects@secret.services
SMTP_PASS: secret
SMTP_SSL: true
SMTP_STARTTLS: true
SMTP_AUTHENTICATION: :login
```
