### ISSUE TITLE
Suport: Error with databases URLs

### ISSUE THREAD

**Issue by htrcc99** [docmost/docmost#171]
I am trying to initialize the project, but I keep getting the error that the postgresql and redis urls are not valid. I would appreciate any help. 

Attached is the docker compose. 

```
version: "3"

services:
  docmost:
    image: docmost/docmost:latest
    container_name: docmost_app
    depends_on:
      - docmost_postgre
      - docmost_redis
    environment:
      APP_URL: "https://docmost.example.com"
      APP_SECRET: "SCqcZckgPwB8r5kXraXRSjbnz79faP4g"
      DATABASE_URL: "postgresql://docmost:7HkxN5NmsR3n753D8ATgxx3bj9Cha6MB@docmost_postgre:5432/docmost?schema=public"
      REDIS_URL: "redis://docmost_redis:6379"
    networks:
      - docmost
    expose:
      - 3000
    restart: unless-stopped
    volumes:
      - ./data/docmost:/app/data/storage

  docmost_postgre:
    image: postgres:16-alpine
    container_name: docmost_postgre
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: 7HkxN5NmsR3n753D8ATgxx3bj9Cha6MB
    restart: unless-stopped
    networks:
      - docmost
    expose:
      - 5432
    volumes:
      - db_data:/var/lib/postgresql/data

  docmost_redis:
    image: redis:7.2-alpine
    container_name: docmost_redis
    restart: unless-stopped
    networks:
      - docmost
    expose:
      - 6379
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:

networks:
  docmost:
    external: true
```
