### ISSUE TITLE
SMTP not working

### ISSUE THREAD

**Issue by kbkozlev** [docmost/docmost#205]
Hi all I tried setting up an SMTP service using Mailjet.

I have tested the configuration though and online SMTP testing site, so I have confirmed that the service is working.

This part of my docker compose file 
```
services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://wiki.MyService.com'
      APP_SECRET: 'Secret'
      DATABASE_URL: 'postgresql://docmost:PASS@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
      SMTP_HOST: "in-v3.mailjet.com"
      SMTP_PORT: 587
      SMTP_USERNAME: "API KEY"
      SMTP_PASSWORD: "API SECRET KEY"
      SMTP_FROM_EMAIL: "docmost@MyDomain.com"
```

I have recreated the docker container with `docker compose up -d` and I tried to invite a new user to the workspace to see if an e-mail will be sent. This has not happened, no matter what I tried.
