### ISSUE TITLE
[Feature Request]: Custom Bullet List Icons

### ISSUE THREAD

**Issue by Shadowfita** [docmost/docmost#207]
Could there be scope for custom icons to be used for items in a list? Perhaps making use of the emojis as icons similar to what's done for pages. 

Potentially achieved by overriding tiptap editor styles. E.g.,

```css
ul:nth-child(1)>li::marker {
    content: "📁"
};
```

To maintain markdown export compatibility, export function could just inline the icon character. E.g.,

```markdown
- 📁 Item 1
    - 🔗 Item 2
```
