### ISSUE TITLE
Markdown Import Showing Only first heading, No Content

### ISSUE THREAD

**Issue by raushanraja** [docmost/docmost#242]
I am experiencing an issue with importing Markdown files. The file imports successfully, the data is sent to the backend, and we receive a 200 response. However, when attempting to view the new page, only the first heading is displayed, and no other content is visible.

Steps to Reproduce

-  Import a Markdown file.
-  The import completes successfully, and we receive a 200 response from the backend.
-   Navigate to the new page.

Also seeing this: Firefox can’t establish a connection to the server at ws://localhost:3000/collab in the console log. The APP_URL env var is set correctly and I am able to access docmost on that url.

Environment
    Browser: Firefox
    Server: Custom hosted server with https
    Docmost version: v0.3.0

### Import Network Request
![2024-09-03-103342_954x512_scrot](https://github.com/user-attachments/assets/6c4748fd-cad9-4a58-98d0-ae45304e5a23)

### Import Network Response
![2024-09-03-103351_951x521_scrot](https://github.com/user-attachments/assets/76850ccf-cc3d-491f-88ca-1dbc1025f22c)

### Test2 Page Display & Console logError 
![2024-09-03-102656_1910x479_scrot](https://github.com/user-attachments/assets/780a242a-1837-4856-ae28-d7592fd171aa)

### README.md file
![2024-09-03-102624_953x516_scrot](https://github.com/user-attachments/assets/cbd7d78b-e281-4289-b3d9-88eff6efa327)

**Comment by raushanraja** [comment]
```yaml
networks:
  reverse_proxy:
    external: true

volumes:
  docmost_data:
  docmost_db_data:
  docmost_redis_data:

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - docmostdb
      - docmostredis
    env_file: ./.env
    environment:
      - APP_URL="https://note.devnode.in"
    restart: unless-stopped
    volumes:
      - docmost_data:/app/data/storage
    networks:
        - reverse_proxy


  docmostdb:
    image: postgres:16-alpine
    env_file: ./.env
    restart: unless-stopped
    volumes:
      - docmost_db_data:/var/lib/postgresql/data
    networks:
        - reverse_proxy


  docmostredis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - docmost_redis_data:/data
    networks:
        - reverse_proxy
```
