### ISSUE TITLE
Blank page on new install / Workspace not found. 

### ISSUE THREAD

**Issue by realdavidops** [docmost/docmost#28]
Brand new install using docker compose. Nothing out of the ordinary in terms of installation. 

Compose file in use:
```
version: "3"

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: "http://localhost:3000"
      APP_SECRET: "SCRUBBED"
      DATABASE_URL: "postgresql://docmost:SCRUBBED@db:5432/docmost?schema=public"
      REDIS_URL: "redis://redis:6379"
    ports:
      - "8758:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: SCRUBBED
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data:
```

I've tried recreating the stack a few times and have erased the volumes inbetween, no dice. All I get is a blank screen. Inspecting the console shows a 415 error, with the following failed load: 

```
// 20240630202851
// https://SCRUBBED/api/users/me

{
  "message": "Workspace not found",
  "error": "Not Found",
  "statusCode": 404
}
```

I also attempted to manually navigate to `/setup/register` but get a similar response. 

Tried firefox/chrome/safari. No luck.

Server info: 
```
$ cat /etc/debian_version
11.7
$ uname -a
Linux docker 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux
$ docker -v
Docker version 24.0.2, build cb74dfc
```
