### ISSUE TITLE
[BUG] missing UI after fresh docker compose setup

### ISSUE THREAD

**Issue by SimonMeysman** [docmost/docmost#363]
This looks like very promising product, and I wanted to test it out locally. The docker compose works perfectly as far as I can see. However, after the inital project setup I am left with a very empty page and seemingly missing UI elements. 
![image](https://github.com/user-attachments/assets/f13df8d2-d88e-4d5a-9a80-93dfcdd5c663)

I used the following docker-compose.yml
```
services:
  docmost:
    image: docmost/docmost:0.3.1
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://127.0.0.1:3000'
      APP_SECRET: '2f4a45e7c629d336a72045fcb991b4d7bca563dcaa5b8715ddbdc6d2c1642b0c'
      DATABASE_URL: 'postgresql://docmost:docmost@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: docmost
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data:
```

All of the docker logs and webbroser logs are clear, and I can connect to the postgresql db with the credentials provided.
