### ISSUE TITLE
[BUG] Incorrect url validation (DATABASE_URL, REDIS_URL)

### ISSUE THREAD

**Issue by SuvorovAM** [docmost/docmost#499]
If the name of the container contains the name of the protocol, then a validation error occurs.

Error messages:
```
...
The Environment variables has failed the following validations:
{"isUrl":"DATABASE_URL must be a valid postgres connection string"}
{"isUrl":"REDIS_URL must be a valid redis connection string"}
Please fix the environment variables and try again. Exiting program...
...
```

docker-compose.yml
```yaml
services:
  project-docmost_app:
    image: docmost/docmost:0.5.0
    container_name: project-docmost_app
    environment:
      DATABASE_URL: "postgresql://app:pass@project-docmost_postgres:5432/app?schema=public"
      REDIS_URL: "redis://project-docmost_redis:6379"
    ...


  project-docmost_postgres:
    image: postgres:16-alpine
    container_name: project-docmost_postgres
    ...
  
  project-docmost_redis:
    image: redis:7.2-alpine
    container_name: project-docmost_redis
    ...

```
___

Upd:
The error appears if there is a `_` character in the connection string

> [!WARNING]
>  ```
>        DATABASE_URL: "postgresql://app:pass@project-docmost_postgres:5432/app?schema=public"
>        REDIS_URL: "redis://project-docmost_redis:6379"
>  ```

> [!TIP]
> ```
>       DATABASE_URL: "postgresql://app:pass@project-docmost-postgres:5432/app?schema=public"
>       REDIS_URL: "redis://project-docmost-redis:6379"
> ```

Upd 2:
The error appears if there is a `?` character in postgres password in the connection string
