### ISSUE TITLE
not syncing from different machines.

### ISSUE THREAD

**Issue by lephtHanded** [docmost/docmost#584]
Issue:
- i *haven't* tested with different browsers on the same machine.
- using chrome on my work laptop, I created a lot of  pages with a lot of content (spreadsheets, links, lists)
- visit the same site on my personal machine, the pages I created are there, but the content is all gone.

- i visit the site again with my work laptop and all the pages and data are still there.

my setup is connecting through Nginx Proxy Manager

**Comment by Philipinho** [comment]
Are you  using a reverse proxy? Do you have websocks enabled?

**Comment by Philipinho** [comment]
Please check if the /collab websocket path (browser console) is connected and transmits data when you type.

**Comment by lephtHanded** [comment]
it looked as though they were all pending:
![image](https://github.com/user-attachments/assets/3afcb21e-324e-41bb-8271-b2b34533e893)
but after a bit... it all started to flood in.

i'll check on my other machine later and see if it shows up on my home machine.

**Comment by lephtHanded** [comment]
> Please check if the /collab websocket path (browser console) is connected and transmits data when you type.

so i accessed a page from the work computer that came up fine, and then checked from my home computer.
this is the console output for the web sockets:
![image](https://github.com/user-attachments/assets/fcf760c2-fcee-4fb8-8ffa-20b39fc9bb5c)

the page didn't load on my personal machine.

**Comment by lephtHanded** [comment]
running this on my pi. (pi 5 2GB ram)
just checked the docker logs and saw this in the docmost-redis container:
![image](https://github.com/user-attachments/assets/2cac75d4-fc21-4371-bdd3-680bb79c157a)

**Comment by lephtHanded** [comment]
looking at my setup - i think i see the issue.
i'll fix it from my work computer tomorrow in case all the data I put up there is in it's cache.

**Comment by lephtHanded** [comment]
PICNIC
I messed up a little in my docker compose file.
fixed it and everything is working now.

**Comment by Philipinho** [comment]
I am glad you figured it out.
Thanks for the update.

**Comment by LQ753799168** [comment]
> I messed up a little in my docker compose file.

Brother, can you share how you solved it? Did you modify docker compose file

**Comment by lephtHanded** [comment]
yeah.
here is my docker compose.
what happened was that i renamed each of the support apps to dm-redis and dm-db
I was smart enough to rename the DB url to the new name, but forgot to modify the redis URL 
After I did that, everything worked.
```
#run on 7101
services:
  docmost:
    image: docmost/docmost:latest
    container_name: docmost7101
    depends_on:
      - dm-db
      - dm-redis
    environment:
      APP_URL: 'https://my.server.com'
      APP_SECRET: '{blah blah blah}'
      DATABASE_URL: 'postgresql://docmost:{somepassword}@dm-db:5432/docmost?schema=public'
      REDIS_URL: 'redis://dm-redis:6379'
    ports:
      - "7101:3000"
    restart: always
    volumes:
      - ${DKRpath}/services/docmost/app:/app/data/storage
      #- docmost:/app/data/storage

  dm-db:
    image: postgres:16-alpine
    container_name: docmstDB
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: {somepassword}
    restart: always
    volumes:
      - ${DKRpath}/services/docmost/deebee:/var/lib/postgresql/data
      #- docmostdb:/var/lib/postgresql/data

  dm-redis:
    image: redis:7.2-alpine
    container_name: docmstREDIS
    restart: always
    volumes:
      - dmredis_data:/data

volumes:
  dmredis_data:
  #docmost:
  #docmostdb:  
```
