### ISSUE TITLE
The tab size of the code block does not meet expectations.

### ISSUE THREAD

**Issue by ijustyce** [docmost/docmost#649]
My code is as follows
```go
func sayHelloStream() {
	conn, _ := createConn()
	if conn == nil {
		return
	}
}
```
And the screenshot of IntelliJ IDEA is as follows

<img width="292" alt="Image" src="https://github.com/user-attachments/assets/3f9ace7d-dbf2-410a-89d9-7fb1b608dd6a" />

Maybe I just want to set the tab size to 2 instead of 4. Is it possible in the future?

**Comment by morrolinux** [comment]
This is of particular relevance considering that code blocks have "reflow"/wrap-around always enabled without an option to disable it and just scroll horizontally for large code snippets.

**Comment by ijustyce** [comment]
> This is of particular relevance considering that code blocks have "reflow"/wrap-around always enabled without an option to disable it and just scroll horizontally for large code snippets.

Add tab-size to css is enough.
```css
.ProseMirror pre code {
    color: inherit;
    padding: 0;
    background: none;
    font-size: var(--mantine-font-size-sm);
    tab-size: 4;
    -moz-tab-size: 4;
    -o-tab-size: 4;
}
```
