### ISSUE TITLE
Picture upload is not working: Error processing file upload.

### ISSUE THREAD

**Issue by Marcel-Lohmann** [docmost/docmost#803]
Hello everyone,

I can't upload images to my Docmost instance.
Every attempt ends with the response: “Error processing file upload.”

The log from Portainer shows me the following:

> [Nest] 40  - 02/26/2025, 5:57:24 PM   ERROR [AttachmentService] Error uploading file to drive:
> 
> [Nest] 40  - 02/26/2025, 5:57:24 PM   ERROR [AttachmentService] Error: Failed to upload file: EACCES: permission denied, mkdir '/app/data/storage/019536a4-61d1-76fe-aa36-04af080f90e3'
> 
>     at LocalDriver.upload (/app/apps/server/dist/integrations/storage/drivers/local.driver.js:19:19)
> 
>     at async StorageService.upload (/app/apps/server/dist/integrations/storage/storage.service.js:25:9)
> 
>     at async AttachmentService.uploadToDrive (/app/apps/server/dist/core/attachment/services/attachment.service.js:152:13)
> 
>     at async AttachmentService.uploadFile (/app/apps/server/dist/core/attachment/services/attachment.service.js:60:9)
> 
>     at async AttachmentController.uploadFile (/app/apps/server/dist/core/attachment/attachment.controller.js:82:34)
> 
> [Nest] 40  - 02/26/2025, 5:57:24 PM   ERROR [AttachmentController] BadRequestException: Error uploading file to drive
> 
>     at AttachmentService.uploadToDrive (/app/apps/server/dist/core/attachment/services/attachment.service.js:156:19)
> 
>     at async AttachmentService.uploadFile (/app/apps/server/dist/core/attachment/services/attachment.service.js:60:9)
> 
>     at async AttachmentController.uploadFile (/app/apps/server/dist/core/attachment/attachment.controller.js:82:34) {
> 
>   response: {
> 
>     message: 'Error uploading file to drive',
> 
>     error: 'Bad Request',
> 
>     statusCode: 400
> 
>   },
> 
>   status: 400,
> 
>   options: {}

There seems to be an error when creating a folder, which I don't understand.
My Docker Compose looks like this:

```
version: "3"

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: "https://docmost.myStarto.eu:MyOpenPort" #"http://localhost:3000"
      APP_SECRET: "PasswortVerrateIchNicht"
      DATABASE_URL: "postgresql://docmost:STRONG_DB_PASSWORD@db:5432/docmost?schema=public"
      REDIS_URL: "redis://redis:6379"
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - /volume1/docker/dockmost/docmost:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: STRONG_DB_PASSWORD
    restart: unless-stopped
    volumes:
      - /volume1/docker/dockmost/db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - /volume1/docker/dockmost/redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data:
```

My Ngingx Proxy Manager settings are as follows:

![Image](https://github.com/user-attachments/assets/ec2132fd-5895-4b44-8b87-610e5b999189)

Text is saved and retained so far
The volumes are all already present.
Do I need to set anything else?
